/**
 * Hiking boots seed data — 28 entries, sourced from Ross's curated wishlist.
 *
 * Specs schema (boots category):
 *   hanwag_class       'A'..'D' Hanwag stiffness rating (A=flex, D=rigid)
 *   cut                'low' | 'mid' | 'high'
 *   field_of_application, terrain_use_case   short descriptors
 *   upper, outsole, waterproofing            material/membrane strings
 *   weight_g_per_shoe / weight_g_pair         grams
 *   crampon_compat     'B0' | 'B1' | 'B2' | 'B3'
 *   crampon_notes      original wording from manufacturer
 *   insulation         text when insulated, omitted otherwise
 *   key_features       array of short feature bullets
 *   url                manufacturer link
 *
 * msrp is pence. Re-run `npm run db:seed` to upsert (idempotent on slug).
 */

import type { Prisma } from "@prisma/client";

type BootSeed = Omit<Prisma.ProductCreateInput, "id" | "createdAt" | "updatedAt">;

export const boots: BootSeed[] = [
  {
    slug: "meindl-philadelphia-men-gtx-walking-shoe",
    name: "Philadelphia Men GTX Walking Shoe",
    brand: "Meindl",
    category: "boots",
    description: "Low-cut, Gore-Tex lined boot for leisure & urban walking. Hanwag class A.",
    msrp: 19999, // £199.99
    specs: {
      hanwag_class: "A",
      cut: "low",
      field_of_application: "Leisure & Urban Walking",
      terrain_use_case: "Low-level trails, everyday walks, urban use; long hikes to everyday wear",
      upper: "Waxed Nubuck leather",
      outsole: "Meindl Comfort Sport sole",
      waterproofing: "GORE-TEX",
      crampon_compat: "B0",
      crampon_notes: "No",
      key_features: ["Grade A", "Comfort-Fit wide toe box", "Air-Active Wellness Sport footbed", "GORE-TEX lining"],
      url: "https://www.meindl.co.uk/product/footwear/mens/philadelphia-gtx/",
    },
  },
  {
    slug: "salewa-pedroc-powertex-shoe-men",
    name: "Pedroc Powertex Shoe Men",
    brand: "Salewa",
    category: "boots",
    description: "Low-cut, Powertex boot for speed hiking. Hanwag class A/B.",
    msrp: 17500, // £175.00
    specs: {
      hanwag_class: "A/B",
      cut: "low",
      field_of_application: "Speed Hiking",
      terrain_use_case: "Fast & light trails, speed hikes, versatile mountain terrain",
      upper: "Ripstop PE mesh, 3F System with Kevlar® Cables, Kevlar core, TPU rand",
      outsole: "Pomoca Speed Hiker Pro",
      waterproofing: "Powertex (PFC-Free)",
      weight_g_per_shoe: 345,
      weight_g_pair: 690,
      crampon_compat: "B0",
      crampon_notes: "No",
      key_features: ["Ultra-lightweight", "3F System", "Pomoca Speed Hiker Pro", "PFC-Free Powertex"],
      url: "https://www.salewa.com/en-gb/pedroc-powertex-shoe-men-00-0000061420",
    },
  },
  {
    slug: "scarpa-cyrus-2-mid-gtx",
    name: "Cyrus 2 Mid GTX",
    brand: "Scarpa",
    category: "boots",
    description: "Mid-cut, Gore-Tex lined boot for hiking & travel. Hanwag class A/B.",
    msrp: 19000, // £190.00
    specs: {
      hanwag_class: "A/B",
      cut: "mid",
      field_of_application: "Hiking & Travel",
      terrain_use_case: "Paths, trails, countryside walks, summer hills, travel & everyday outdoor use",
      upper: "1.8–2.0 mm nubuck leather",
      outsole: "SCARPA PRESA (Super gum compound, self-cleaning lug)",
      waterproofing: "GORE-TEX ePE (Bluesign®, PFAS-Free)",
      weight_g_per_shoe: 460,
      weight_g_pair: 920,
      crampon_compat: "B0",
      crampon_notes: "No",
      key_features: ["PFAS-Free GORE-TEX ePE", "PRESA Super Gum outsole", "EVA midsole", "Bonded-strobel", "Resoleable"],
      url: "https://www.scarpa.co.uk/products/cyrus-2-mid-gtx-mens-walking-boots",
    },
  },
  {
    slug: "scarpa-rove-rock-s-gtx",
    name: "Rove Rock S GTX",
    brand: "Scarpa",
    category: "boots",
    description: "Low-cut, Gore-Tex lined boot for lifestyle / approach. Hanwag class A/B.",
    msrp: 21000, // £210.00
    specs: {
      hanwag_class: "A/B",
      cut: "low",
      field_of_application: "Lifestyle / Approach",
      terrain_use_case: "City streets to mountain trails; climbing wall commutes; all-day versatile use",
      upper: "Full suede (suede-idro) + mesh fabric + protective suede band",
      outsole: "Spyder Cross (Vibram® trail-running inspired, variable density)",
      waterproofing: "GORE-TEX® ePE (PFAS-Free)",
      weight_g_per_shoe: 400,
      weight_g_pair: 800,
      crampon_compat: "B0",
      crampon_notes: "No",
      key_features: ["Vibram trail-running sole", "Spyder Cross midsole", "Tape lacing", "GORE-TEX ePE", "City + trail"],
      url: "https://www.scarpa.co.uk/products/rove-rock-s-gtx-waterproof-walking-shoe",
    },
  },
  {
    slug: "hagl-fs-l-i-m-horizon-hike-gtx-low-men",
    name: "L.I.M Horizon Hike GTX Low Men",
    brand: "Haglöfs",
    category: "boots",
    description: "Low-cut, Gore-Tex lined boot for fast hiking & trail. Hanwag class A/B.",
    msrp: 15000, // £150.00
    specs: {
      hanwag_class: "A/B",
      cut: "low",
      field_of_application: "Fast Hiking & Trail",
      terrain_use_case: "Fast-paced on/off trail adventures; wet & variable terrain; lightweight day use",
      upper: "Ripstop fabric + abrasion-resistant TPU film overlays (PFAS-Free)",
      outsole: "Vibram® Traction Lug (XS Trek compound, Vibram SLE EVA midsole)",
      waterproofing: "GORE-TEX ePE 3L (PFAS-Free, bluesign®)",
      weight_g_per_shoe: 430,
      weight_g_pair: 860,
      crampon_compat: "B0",
      crampon_notes: "No",
      key_features: ["L.I.M ultralight", "Vibram Traction Lug (+25% traction)", "GORE-TEX 3L", "Reinforced toes & heels"],
      url: "https://www.haglofs.com/en/men/shoes-boots-men/shoes-boots-hiking-shoes-hiking-boots-men/shoes-boots-hiking-boots-hiking-shoes-hiking-shoes-men/lim-fh-ii-gtx-low-men-6082905SP",
    },
  },
  {
    slug: "salomon-x-ultra-360-leather-gtx",
    name: "X Ultra 360 Leather GTX",
    brand: "Salomon",
    category: "boots",
    description: "Low-cut, Gore-Tex lined boot for hiking & day use. Hanwag class A/B.",
    msrp: 14000, // £140.00
    specs: {
      hanwag_class: "A/B",
      cut: "low",
      field_of_application: "Hiking & Day Use",
      terrain_use_case: "Single-day hikes on easy to mixed paths; light trails; everyday outdoor use",
      upper: "Nubuck leather + Synthetic mesh/textile",
      outsole: "All Terrain contaGRIP® (rubber)",
      waterproofing: "GORE-TEX",
      weight_g_per_shoe: 397,
      weight_g_pair: 794,
      crampon_compat: "B0",
      crampon_notes: "No",
      key_features: ["quickLACE™ one-pull", "advancedChassis", "contaGRIP® All Terrain", "OrthoLite®", "sensiFIT™", "EnergyCell EVA", "10mm drop"],
      url: "https://www.salomon.com/en-gb/product/x-ultra-360-leather-gore-tex-li5970/L47571400",
    },
  },
  {
    slug: "columbia-tellurix-titanium-outdry-men",
    name: "Tellurix Titanium Outdry Men",
    brand: "Columbia",
    category: "boots",
    description: "Low-cut, OutDry™ Extreme boot for trail hiking. Hanwag class A/B.",
    msrp: 12500, // £125.00
    specs: {
      hanwag_class: "A/B",
      cut: "low",
      field_of_application: "Trail Hiking",
      terrain_use_case: "Mixed trails, wet conditions, technical terrain; day hikes with waterproof performance",
      upper: "Technical mesh with NavicFit™ midfoot lock, no-sew TPU overlays",
      outsole: "Vibram® Megagrip (multi-directional lugs, mud release)",
      waterproofing: "OutDry™ Extreme",
      weight_g_per_shoe: 369,
      weight_g_pair: 738,
      crampon_compat: "B0",
      crampon_notes: "No",
      key_features: ["OutDry™ Extreme waterproofing", "Vibram® Megagrip", "NavicFit™ midfoot lock", "Omni-MAX™ cushioning", "Techlite+™ midsole"],
      url: "https://www.columbiasportswear.co.uk/p/mens-tellurix-titanium-outdry-hiking-shoe-199141156148.html",
    },
  },
  {
    slug: "salewa-pedroc-pro-powertex-mid-boot-men",
    name: "Pedroc Pro Powertex Mid Boot Men",
    brand: "Salewa",
    category: "boots",
    description: "Mid-cut, Powertex boot for speed hiking. Hanwag class B.",
    msrp: 20000, // £200.00
    specs: {
      hanwag_class: "B",
      cut: "mid",
      field_of_application: "Speed Hiking",
      terrain_use_case: "Technical speed hiking, versatile mountain terrain, moderate trails",
      upper: "Ripstop PE mesh, 3F System with Kevlar® Cables, Kevlar core, TPU rand",
      outsole: "Pomoca Speed Hiker Pro",
      waterproofing: "Powertex (PFC-Free)",
      weight_g_per_shoe: 390,
      weight_g_pair: 780,
      crampon_compat: "B0",
      crampon_notes: "No",
      key_features: ["Mid-cut technical speed boot", "3F System", "Pomoca Speed Hiker Pro", "PFC-Free Powertex"],
      url: "https://www.salewa.com/en-gb/pedroc-pro-powertex-mid-boot-men-00-0000061418",
    },
  },
  {
    slug: "salewa-alp-trainer-2-mid-gore-tex-mens-shoe",
    name: "Alp Trainer 2 Mid GORE-TEX® Men's Shoe",
    brand: "Salewa",
    category: "boots",
    description: "Mid-cut, Gore-Tex lined boot for trekking & hiking. Hanwag class B.",
    msrp: 20000, // £200.00
    specs: {
      hanwag_class: "B",
      cut: "mid",
      field_of_application: "Trekking & Hiking",
      terrain_use_case: "Alpine hiking, moderate–difficult mountain trails, all-day use",
      upper: "Suede 1.4–1.6 mm, Protective rand, 3F System with Steel Cables",
      outsole: "Vibram® Alpine Hiking",
      waterproofing: "GORE-TEX® Extended Comfort",
      weight_g_per_shoe: 552,
      weight_g_pair: 1104,
      crampon_compat: "B0",
      crampon_notes: "No",
      key_features: ["Vibram Alpine Hiking", "GORE-TEX Extended Comfort", "3F System", "MFF+ footbed"],
      url: "https://www.salewa.com/en-gb/alp-trainer-2-mid-gore-tex_-men_s-shoe-00-0000061382",
    },
  },
  {
    slug: "hanwag-makra-trek-gtx",
    name: "Makra Trek GTX",
    brand: "Hanwag",
    category: "boots",
    description: "Mid-cut, Gore-Tex lined boot for trekking. Hanwag class B.",
    msrp: 26500, // £265.00
    specs: {
      hanwag_class: "B",
      cut: "mid",
      field_of_application: "Trekking",
      terrain_use_case: "Demanding mountain hikes up to 3,000 m; stony/rocky paths with heavy pack",
      upper: "Suede + Textile (Perwanger leather)",
      outsole: "Vibram® Integral Light",
      waterproofing: "GORE-TEX",
      weight_g_per_shoe: 635,
      weight_g_pair: 1270,
      crampon_compat: "B0",
      crampon_notes: "No",
      key_features: ["Vibram Integral Light", "Hanwag 2 Zone Lock", "GORE-TEX", "Resoleable", "Made in Croatia"],
      url: "https://www.hanwag.com/uk/en-gb/men/trekking/long-distance-treks/makra-trek-gtx/",
    },
  },
  {
    slug: "meindl-guffert-men-gtx-walking-boot",
    name: "Guffert Men GTX Walking Boot",
    brand: "Meindl",
    category: "boots",
    description: "High-cut, Gore-Tex lined boot for trekking & hiking. Hanwag class B.",
    msrp: 36999, // £369.99
    specs: {
      hanwag_class: "B",
      cut: "high",
      field_of_application: "Trekking & Hiking",
      terrain_use_case: "Demanding day hikes & mountain paths; Lake District, North Wales, Scotland, lower Alps",
      upper: "Oiled Nubuck leather",
      outsole: "Vibram® Multigriff",
      waterproofing: "GORE-TEX",
      crampon_compat: "B0",
      crampon_notes: "No",
      key_features: ["MFS Memory Foam", "Vibram Multigriff", "GORE-TEX", "Digafix lacing", "Comfort-Fit cork & fleece footbed"],
      url: "https://www.meindl.co.uk/product/footwear/mens/guffert-gtx/",
    },
  },
  {
    slug: "scarpa-ladakh-gtx",
    name: "Ladakh GTX",
    brand: "Scarpa",
    category: "boots",
    description: "High-cut, Gore-Tex lined boot for trekking & hiking. Hanwag class B.",
    msrp: 32000, // £320.00
    specs: {
      hanwag_class: "B",
      cut: "high",
      field_of_application: "Trekking & Hiking",
      terrain_use_case: "Big day hikes & multi-day treks; fell walking, rocky mountain terrain with heavy pack",
      upper: "2.4–2.6 mm nubuck leather with full rubber protection",
      outsole: "Vibram® (Biometric Fly, Tront rubber compound)",
      waterproofing: "GORE-TEX ePTFE More Seasons",
      weight_g_per_shoe: 825,
      weight_g_pair: 1650,
      crampon_compat: "B0",
      crampon_notes: "No",
      key_features: ["Biometric Fly PU midsole", "Vibram Tront compound", "3D Auto-Fit Ankle Collar", "ACTIVfit", "Resoleable"],
      url: "https://www.scarpa.co.uk/products/ladakh-gtx-leather-walking-boots",
    },
  },
  {
    slug: "hagl-fs-rosson-fg-proof-mid-men",
    name: "Rosson FG Proof Mid Men",
    brand: "Haglöfs",
    category: "boots",
    description: "Mid-cut, PROOF™ boot for trekking & hiking. Hanwag class B.",
    msrp: 16000, // £160.00
    specs: {
      hanwag_class: "B",
      cut: "mid",
      field_of_application: "Trekking & Hiking",
      terrain_use_case: "Variable terrain trekking; wet conditions; supportive trail use with lighter loads",
      upper: "Full-grain leather (LWG-certified, PFAS-free DWR)",
      outsole: "Rubber outsole (high-traction patterned)",
      waterproofing: "PROOF™ (fluorocarbon-free, 64% recycled polyester)",
      weight_g_per_shoe: 550,
      weight_g_pair: 1100,
      crampon_compat: "B0",
      crampon_notes: "No",
      key_features: ["PROOF™ membrane", "LWG full-grain leather", "Molded EVA midsole", "Rearfoot cushioning", "Tongue gussets"],
      url: "https://www.haglofs.com/en/men/shoes-boots-men/shoes-boots-hiking-shoes-hiking-boots-men/shoes-boots-hiking-boots-hiking-shoes-hiking-shoes-men/haglofs-rosson-fg-proof-mid-men-6083912C5",
    },
  },
  {
    slug: "hagl-fs-ridge-gtx-ii-mid-men",
    name: "Ridge GTX II Mid Men",
    brand: "Haglöfs",
    category: "boots",
    description: "Mid-cut, Gore-Tex lined boot for trekking & hiking. Hanwag class B.",
    msrp: 20000, // £200.00
    specs: {
      hanwag_class: "B",
      cut: "mid",
      field_of_application: "Trekking & Hiking",
      terrain_use_case: "Wet conditions & varied mountain terrain; extra ankle support; heavy loads",
      upper: "Nubuck leather",
      outsole: "Rubber outsole (wet grip traction)",
      waterproofing: "GORE-TEX Extended Comfort (Gore 3L, PFAS-free)",
      weight_g_per_shoe: 1020,
      weight_g_pair: 2040,
      crampon_compat: "B0",
      crampon_notes: "No",
      key_features: ["GORE-TEX 3L", "Torsional stability chassis", "Molded rubber-reinforced toes & heels", "Rearfoot cushioning"],
      url: "https://www.haglofs.com/en/men/shoes-boots-men/shoes-boots-hiking-shoes-hiking-boots-men/shoes-boots-hiking-boots-hiking-shoes-hiking-shoes-men/haglofs-ridge-gtx-ii-mid-men-6082805QH",
    },
  },
  {
    slug: "hagl-fs-solid-pro-2-gtx-mid",
    name: "Solid Pro 2 GTX Mid",
    brand: "Haglöfs",
    category: "boots",
    description: "High-cut, Gore-Tex lined boot for trekking & hiking. Hanwag class B.",
    msrp: 24000, // £240.00
    specs: {
      hanwag_class: "B",
      cut: "high",
      field_of_application: "Trekking & Hiking",
      terrain_use_case: "Bold treks with heaviest loads; demanding mountain terrain; all-season use",
      upper: "1.9 mm full-grain leather (PFAS-free, LWG Gold/Silver rated)",
      outsole: "Vibram® XS-Trek EVO rubber",
      waterproofing: "GORE-TEX More Seasons Sierra XT 4L",
      weight_g_per_shoe: 760,
      weight_g_pair: 1520,
      crampon_compat: "B0",
      crampon_notes: "No",
      key_features: ["Vibram XS-Trek EVO", "GORE-TEX 4L More Seasons", "EVA + PU heel wedge", "Rubber reinforced toes", "Lace lock"],
      url: "https://www.haglofs.com/en/men/shoes-boots-men/shoes-boots-waterproof-shoes-men/solid-pro-2-gtx-high-6080712C5",
    },
  },
  {
    slug: "lowa-explorer-gtx-mid",
    name: "Explorer GTX Mid",
    brand: "LOWA",
    category: "boots",
    description: "Mid-cut, Gore-Tex lined boot for trekking & hiking. Hanwag class B.",
    msrp: 22000, // £220.00
    specs: {
      hanwag_class: "B",
      cut: "mid",
      field_of_application: "Trekking & Hiking",
      terrain_use_case: "Paths, trails, mountain walking; all-day trekking with heavy loads; comfortable from new",
      upper: "Suede + Rubber & TPU toe/heel cap",
      outsole: "Vibram® TRAC® CONTROL",
      waterproofing: "GORE-TEX",
      weight_g_per_shoe: 550,
      weight_g_pair: 1100,
      crampon_compat: "B0",
      crampon_notes: "No",
      key_features: ["Litecell PU midsole", "Vibram TRAC CONTROL", "X-Lacing tongue lock", "GORE-TEX", "Resoleable", "No break-in"],
      url: "https://www.lowa.co.uk/products/lowa-explorer-gtx-mid",
    },
  },
  {
    slug: "salomon-x-ultra-5-mid-gtx",
    name: "X Ultra 5 Mid GTX",
    brand: "Salomon",
    category: "boots",
    description: "Mid-cut, Gore-Tex lined boot for hiking & day use. Hanwag class B.",
    msrp: 16500, // £165.00
    specs: {
      hanwag_class: "B",
      cut: "mid",
      field_of_application: "Hiking & Day Use",
      terrain_use_case: "All-day hikes on wet, rocky & muddy terrain; mixed mountain paths; demanding trails",
      upper: "Matryx® (Kevlar® high-tenacity yarn) + PU coated leather/Textile",
      outsole: "All Terrain contaGRIP® (rubber)",
      waterproofing: "GORE-TEX",
      weight_g_per_shoe: 454,
      weight_g_pair: 908,
      crampon_compat: "B0",
      crampon_notes: "No",
      key_features: ["advancedChassis", "Matryx® Kevlar® upper", "Active Support wings", "contaGRIP®", "sensiFIT™", "EnergyCell EVA", "11mm drop"],
      url: "https://www.salomon.com/en-gb/product/x-ultra-5-mid-gore-tex-li6287/L47754200",
    },
  },
  {
    slug: "scarpa-ribelle-cross-2-gtx",
    name: "Ribelle Cross 2 GTX",
    brand: "Scarpa",
    category: "boots",
    description: "Low-cut, Gore-Tex lined boot for approach / technical trail. Hanwag class B.",
    msrp: 16000, // £160.00
    specs: {
      hanwag_class: "B",
      cut: "low",
      field_of_application: "Approach / Technical Trail",
      terrain_use_case: "Technical trails, fast hikes, mountain approaches, wet & variable terrain; 3-season use",
      upper: "ONE-LAYER technical fabric + TPU overlays; protective TPU Rand",
      outsole: "Presa® HIK-06 (high-traction for rocky & wet terrain)",
      waterproofing: "GORE-TEX® ePE",
      weight_g_per_shoe: 210,
      weight_g_pair: 420,
      crampon_compat: "B0",
      crampon_notes: "No",
      key_features: ["GORE-TEX® ePE", "Presa® HIK-06 sole", "TPU Rand", "Shock-absorbing midsole", "10mm drop", "Ribelle Run heritage"],
      url: "https://www.scarpa.co.uk/products/ribelle-cross-2-gtx-lightweight-mens-walking-shoes",
    },
  },
  {
    slug: "scarpa-ribelle-cross-2-mid-gtx",
    name: "Ribelle Cross 2 Mid GTX",
    brand: "Scarpa",
    category: "boots",
    description: "Mid-cut, Gore-Tex lined boot for approach / technical trail. Hanwag class B.",
    msrp: 17500, // £175.00
    specs: {
      hanwag_class: "B",
      cut: "mid",
      field_of_application: "Approach / Technical Trail",
      terrain_use_case: "Technical mountain trails, fast hikes, technical approaches; all-weather 3-season use",
      upper: "ONE-LAYER mesh + TPU overlays; 3D Autofit ankle collar; TPU Rand",
      outsole: "Presa® HIK-06 (high-traction for rocky & wet terrain)",
      waterproofing: "GORE-TEX® ePE",
      weight_g_per_shoe: 223,
      weight_g_pair: 446,
      crampon_compat: "B0",
      crampon_notes: "No",
      key_features: ["GORE-TEX® ePE", "Presa® HIK-06 sole", "3D Autofit ankle collar", "Mid-cut ankle support", "TPU Rand", "10mm drop"],
      url: "https://www.scarpa.co.uk/products/ribelle-cross-2-mid-gtx-lightweight-walking-boots",
    },
  },
  {
    slug: "salewa-pedroc-2-shoe-max-men",
    name: "Pedroc 2 Shoe Max Men",
    brand: "Salewa",
    category: "boots",
    description: "Low-cut boot for speed hiking. Hanwag class B.",
    msrp: 13000, // £130.00
    specs: {
      hanwag_class: "B",
      cut: "low",
      field_of_application: "Speed Hiking",
      terrain_use_case: "Technical trails, mountain terrain; fast-paced speed hiking with maximum cushioning",
      upper: "High-tenacity protective breathable mesh; TPU film protection; 3F System",
      outsole: "Pomoca™ Speed Hiker 2",
      weight_g_per_shoe: 325,
      weight_g_pair: 650,
      crampon_compat: "B0",
      crampon_notes: "No",
      key_features: ["Pomoca™ Speed Hiker 2 outsole", "EVA midsole + stability plate", "3F System", "Wide fit", "TPU film", "Reflective details", "6mm drop"],
      url: "https://www.salewa.com/en-gb/pedroc-2-shoe-max-men-00-0000061475",
    },
  },
  {
    slug: "salewa-puez-winter-mid-powertex-men",
    name: "Puez Winter Mid Powertex Men",
    brand: "Salewa",
    category: "boots",
    description: "High-cut, Powertex boot for trekking & hiking (winter). Hanwag class B/C.",
    msrp: 22000, // £220.00
    specs: {
      hanwag_class: "B/C",
      cut: "high",
      field_of_application: "Trekking & Hiking (Winter)",
      terrain_use_case: "Urban to technical winter conditions; stony mountain paths; all-day cold & wet",
      upper: "High-resistance ripstop PE, 3F System with Kevlar® Cables, Protective PU rand",
      outsole: "POMOCA Alpine Trekker",
      waterproofing: "Powertex (PFC-Free)",
      weight_g_per_shoe: 480,
      weight_g_pair: 960,
      crampon_compat: "B0",
      crampon_notes: "No",
      insulation: "Primaloft + CFF Winter footbed",
      key_features: ["Insulated for winter", "3F System", "POMOCA Alpine Trekker", "Edging Plate 2", "Climbing Lacing"],
      url: "https://www.salewa.com/en-gb/puez-winter-mid-powertex-men-00-0000061447",
    },
  },
  {
    slug: "meindl-island-men-mfs-active-walking-boot",
    name: "Island Men MFS Active Walking Boot",
    brand: "Meindl",
    category: "boots",
    description: "High-cut, Gore-Tex lined boot for trekking & hiking (alpine). Hanwag class B/C.",
    msrp: 34999, // £349.99
    specs: {
      hanwag_class: "B/C",
      cut: "high",
      field_of_application: "Trekking & Hiking (Alpine)",
      terrain_use_case: "Extended mountain treks; robust alpine paths; occasional crampon use; year-round wet",
      upper: "Oiled Nubuck leather",
      outsole: "Vibram® Multigriff",
      waterproofing: "GORE-TEX",
      crampon_compat: "B1",
      crampon_notes: "Occasional (light)",
      key_features: ["MFS Memory Foam", "F31m last", "Vibram Multigriff", "GORE-TEX", "Digafix lacing", "Air-Active drysole"],
      url: "https://www.meindl.co.uk/product/footwear/mens/island-men-mfs-active/",
    },
  },
  {
    slug: "meindl-himalaya-men-mfs-walking-boot",
    name: "Himalaya Men MFS Walking Boot",
    brand: "Meindl",
    category: "boots",
    description: "High-cut, Gore-Tex lined boot for mountain trekking. Hanwag class B/C.",
    msrp: 38250, // £382.50
    specs: {
      hanwag_class: "B/C",
      cut: "high",
      field_of_application: "Mountain Trekking",
      terrain_use_case: "Long treks, snowshoeing, challenging trails; year-round use with crampon suitability",
      upper: "Sil-Nubuck leather",
      outsole: "Meindl Multigriff by Vibram®",
      waterproofing: "GORE-TEX",
      crampon_compat: "B1",
      crampon_notes: "Some suitability",
      key_features: ["MFS Memory Foam", "Meindl Multigriff by Vibram", "GORE-TEX", "Digafix lacing", "Air-Active drysole"],
      url: "https://www.meindl.co.uk/product/footwear/mens/himalaya-mfs/",
    },
  },
  {
    slug: "scarpa-mescalito-trk-pro-gtx",
    name: "Mescalito TRK Pro GTX",
    brand: "Scarpa",
    category: "boots",
    description: "High-cut, Gore-Tex lined boot for trekking (4-season). Hanwag class B/C.",
    msrp: 28500, // £285.00
    specs: {
      hanwag_class: "B/C",
      cut: "high",
      field_of_application: "Trekking (4-Season)",
      terrain_use_case: "Demanding UK mountain terrain (Lakes, Wales, Scotland); winter walking; heavier loads",
      upper: "Water-resistant oiled suede leather + full-grain leather collar",
      outsole: "Vibram® Dynamis TRK (PU Bi-Density midsole)",
      waterproofing: "GORE-TEX® (Bluesign®, PFCec Free)",
      weight_g_per_shoe: 650,
      weight_g_pair: 1300,
      crampon_compat: "B1",
      crampon_notes: "B1 (strap-on crampons)",
      key_features: ["B1 crampon", "Vibram Dynamis TRK", "Anti-fatigue frame", "Comfort Fit Plus midsole", "Resoleable", "4-season"],
      url: "https://www.scarpa.co.uk/products/mescalito-trk-pro-gtx-waterproof-walking-boot",
    },
  },
  {
    slug: "salomon-quest-5-gtx",
    name: "Quest 5 GTX",
    brand: "Salomon",
    category: "boots",
    description: "High-cut, Gore-Tex lined boot for backpacking. Hanwag class B/C.",
    msrp: 20000, // £200.00
    specs: {
      hanwag_class: "B/C",
      cut: "high",
      field_of_application: "Backpacking",
      terrain_use_case: "Multi-day routes on wet, rocky, muddy & snowy terrain; backpacking with heavy loads",
      upper: "Nubuck leather + Ripstop fabric (synthetic)",
      outsole: "All Terrain contaGRIP® (rubber)",
      waterproofing: "GORE-TEX",
      weight_g_per_shoe: 595,
      weight_g_pair: 1190,
      crampon_compat: "B0",
      crampon_notes: "No",
      key_features: ["4D advancedChassis™", "Nubuck + Ripstop", "Gusseted tongue", "contaGRIP®", "sensiFIT™", "EnergyCell EVA", "12mm drop"],
      url: "https://www.salomon.com/en-gb/product/quest-5-gore-tex-li8737/L49138400",
    },
  },
  {
    slug: "scarpa-zodiac-tech-gtx",
    name: "Zodiac Tech GTX",
    brand: "Scarpa",
    category: "boots",
    description: "High-cut, Gore-Tex lined boot for alpine / technical hiking. Hanwag class C.",
    msrp: 29500, // £295.00
    specs: {
      hanwag_class: "C",
      cut: "high",
      field_of_application: "Alpine / Technical Hiking",
      terrain_use_case: "Via ferrata, mixed alpine terrain, scrambling & light mountaineering",
      upper: "Suede Plus Water Resistant 1.6–1.8 mm + Textile",
      outsole: "ABS Precision Cramp (Vibram® Mont rubber)",
      waterproofing: "GORE-TEX® Performance Comfort",
      weight_g_per_shoe: 680,
      weight_g_pair: 1360,
      crampon_compat: "B2",
      crampon_notes: "B2 (semi-automatic crampons)",
      key_features: ["B2 crampon", "BAS Technology", "Vibram Mont rubber", "ABS Precision Cramp sole"],
      url: "https://www.scarpa.co.uk/products/zodiac-tech-gtx-waterproof-walking-boot",
    },
  },
  {
    slug: "salewa-ortles-ascent-mid-gore-tex-boot-men",
    name: "Ortles Ascent Mid Gore-Tex® Boot Men",
    brand: "Salewa",
    category: "boots",
    description: "High-cut, Gore-Tex lined boot for mountaineering / alpine. Hanwag class C/D.",
    msrp: 35000, // £350.00
    specs: {
      hanwag_class: "C/D",
      cut: "high",
      field_of_application: "Mountaineering / Alpine",
      terrain_use_case: "Rock, ice & snow; demanding alpine terrain; semi-crampon-compatible routes",
      upper: "Suede Leather 2.0–2.2 mm, 3F System with Steel Cables, TPU rand, Nylon elastic gaiter",
      outsole: "Vibram® Alpine Guide",
      waterproofing: "GORE-TEX® Insulated Comfort (Duratherm XL)",
      weight_g_per_shoe: 850,
      weight_g_pair: 1700,
      crampon_compat: "B3",
      crampon_notes: "Semi (step-in capable)",
      insulation: "GORE-TEX® Duratherm XL",
      key_features: ["Stiff carbon-loaded Nylon insole", "Vibram Alpine Guide", "Insulated GTX", "3F Steel Cables", "MFF+ footbed"],
      url: "https://www.salewa.com/en-gb/ortles-ascent-mid-gore-tex_-boot-men-00-0000061408",
    },
  },
  {
    slug: "hanwag-omega-gtx",
    name: "Omega GTX",
    brand: "Hanwag",
    category: "boots",
    description: "High-cut, Gore-Tex lined boot for mountaineering / alpine. Hanwag class D.",
    msrp: 47000, // £470.00
    specs: {
      hanwag_class: "D",
      cut: "high",
      field_of_application: "Mountaineering / Alpine",
      terrain_use_case: "High-alpine tours, glaciers, demanding summit routes, rock & ice; extreme altitude",
      upper: "Suede 2.8–3.0 mm thick",
      outsole: "Vibram® Alpin (self-cleaning, insulating)",
      waterproofing: "GORE-TEX",
      weight_g_per_shoe: 1120,
      weight_g_pair: 2240,
      crampon_compat: "B3",
      crampon_notes: "Step-in compatible",
      insulation: "Thermal to –15 °C (DIN EN 344-1)",
      key_features: ["Thermal –15 °C", "Customisable volume", "Vibram Alpin", "Resoleable", "Made in Germany"],
      url: "https://www.hanwag.com/uk/en-gb/men/mountaineering/alpine/omega-gtx/",
    },
  },
];
